### ISSUE TITLE
Escape sequences in replace string (substitute template)

### ISSUE THREAD

**Issue by Forkest** [masterandrey/TRegExpr#2]
are not supported

**Comment by masterandrey** [comment]
Could you please provide me with an example where you need them?

**Comment by Forkest** [comment]
See [here](https://doublecmd.sourceforge.io/mantisbt/view.php?id=1694). It's needed to be able to replace with newlines and other escape sequences that can be used in the search string. Currently the search string cannot be reused as a replace string if it uses escape sequences.

**Comment by masterandrey** [comment]
ReplaceRegExpr(#$d'('#$a')', 'word'#$d#$a, '$1', True);
== 'word'#$a

As expected.


Substitution string preprocessing really very strange.
It is not documented and I do not remember why we need that.
It searchs for \n, \u, \U, \l, \L and treat them as I described now at reqexpstudio.com.

The same code now in FPC so it should work the same.

    ReplaceRegExpr('(word)', 'word', '\U$1\\r', True); // escape '\' so to have it in output. And uppercase all string after \U
    == 'WORD\r'

    ReplaceRegExpr('(word)', 'word', '$1\n', True);
    == 'word'#$d#$a // convert \n into #$d#$a

If you need some preprocessing for the substitution string (like '\r' and so on) do it before passing the string into the substitute function.

**Comment by Forkest** [comment]
I don't exactly understand why do you find it strange. I'll try by example:

    ReplaceRegExpr('\n', 'abc'#$D#$A'def', '\n', True);

Original string: `a b c #13 #10 d e f`
Replaced with FPC-bundled version: `a b c #13 #13 #10 d e f`
Replaced with current git version:  `a b c #13 n d e f`

Do you find this behavior "as expected"?

**Comment by masterandrey** [comment]
The substitute string processing in my repo and in FPC are the same - please share with me the code how do you compare them and have different results.
I would like to fix the difference but do not know how to reproduce it.
The best way - add test into https://github.com/masterandrey/TRegExpr/blob/master/test/tregexpr_tests.pas ).
And I will fix it.

The substitute string processing use special chars '\n', '\u' and so on as I described today on http://regexpstudio.com/en/tregexpr_interface.html, section Substitute.

I think that you 'FPC' version of code somehow preprocess the substitution string before sending to RegExpr and replaces '\n' with #13.
So you see different results, but RegExpr in fact works the same in my repo and in FPC.

RegExpr by itself replaces '\n' in substitution string with #$d#$a.
And '\n' in regular expression is replaced with #$d#$a.

So ReplaceRegExpr('\n', 'abc'#$D#$A'def', '\n', True) is the same as ReplaceRegExpr(#$D#$A, 'abc'#$D#$A'def', #$D#$A, True)

I do not think this is very nice behaviour but it is as described in documentation and was the same last 20 years ;)

And at list I does has some logic.

If you want to preprocess your string c-style backslash encoding for example you can use ExpandCEscapeSequences:
http://www.gnu-pascal.de/gpc/StringUtils.html

**Comment by Forkest** [comment]
For me ReplaceRegExpr('\n', 'abc'#$D#$A'def', '\n', True) is not the same as ReplaceRegExpr(#$D#$A, 'abc'#$D#$A'def', #$D#$A, True). The first one is buggy, the second one works flawlessly, output is the same as input.

I'm using https://www.lazarus-ide.org/
I've just made a fresh install of the latest stable version (1.8.4) with deleting of previous configuration to make sure the bug is reproducible. It is on Windows XP, although it shouldn't matter.

This is how I do it:

Choose New project, select Simple program, the full source code is:

```
uses RegExpr;

var s: string; i: integer;
begin
  s := ReplaceRegExpr('\n', 'abc'#13#10'def', '\n', True);
  writeln(s);
  for i := 1 to length(s) do
    write(ord(s[i]), ' ');
  readln;
end.
```

Run the code to use FPC's version.

Save the project, put the RegExpr.pas downloaded from GitHub nearby, run again.

**Comment by masterandrey** [comment]
Thanks a lot.

Now my version in sync with fpc regrding substitute while replace

``` pascal
uses RegExpr;

var
  r: TRegExpr;
  s: string;
  i: integer;
begin
  r := TRegExpr.Create;
  r.Expression := '\n';
  r.Compile;
  writeln(r.Dump);
  s := r.Replace('abc'#13#10'def', '\n', True);
  writeln(s);
  for i := 1 to length(s) do
    write(ord(s[i]), ' ');
  readln;
end.   
```

**Comment by Forkest** [comment]
But that behavior is wrong too!

Original string: `a b c #13 #10 d e f`
Replaced string: `a b c #13 #13 #10 d e f`
Expected string: `a b c #13 #10 d e f`, the same as original.

ReplaceRegExpr('\n', 'abc'#$D#$A'def', '\n', True) is still not the same as ReplaceRegExpr(#$D#$A, 'abc'#$D#$A'def', #$D#$A, True)

**Comment by Forkest** [comment]
The original idea was to be able to treat substitution string the same way as the search pattern, with all of its \\-behavior, like \r and \x0A

**Comment by masterandrey** [comment]
Well here is the problem.
My initial re compiler treated '\n' in re just as #10.
But for substitution (inside replace) function someone from free pascal decided that \n should be #13#10.
And I just today merge this code with mine.

So if re is '\n' (for TRegExpr this is just #10) and replace string '\n' (fpc team treats that as #10#13) in result we have #13#13#10.

May be the best solution would be treat '\n' as #10 in substitution as well.
But here would be incompatibility with free pascal.


Send them change request?

**Comment by Forkest** [comment]
Then it should be discussed with them, probably, as this would be a backward incompatible change.
But in my opinion it would be great to change it for consistency, so \r \n \etc are treated in the same way in both arguments.

**Comment by masterandrey** [comment]
OK send them pull request https://github.com/graemeg/freepascal/pull/15

**Comment by masterandrey** [comment]
In my version will do the same later - see ticket 7 above

**Comment by Forkest** [comment]
Thanks for implementing it. I hope they will merge it.

**Comment by masterandrey** [comment]
I merged with freepascal version
They did not change default and you have to set .UseOsLineEndOnReplace:=False implicitly
to have new behaviour of '\n' in replace.

**Comment by Forkest** [comment]
Michael Van Canneyt has introduced a new overload, see revision [40056](https://svn.freepascal.org/cgi-bin/viewvc.cgi?view=revision&revision=40056) ([patch](https://svn.freepascal.org/cgi-bin/viewvc.cgi/trunk/packages/regexpr/src/regexpr.pas?r1=40056&r2=40055&pathrev=40056&view=patch)), also a small tests fix in [40057](https://svn.freepascal.org/cgi-bin/viewvc.cgi?view=revision&revision=40057) ([patch](https://svn.freepascal.org/cgi-bin/viewvc.cgi/trunk/packages/regexpr/tests/tcregexp.pp?r1=40057&r2=40056&pathrev=40057&view=patch)). Would you merge these changes?

**Comment by masterandrey** [comment]
Not pretty but do not see better design
https://github.com/masterandrey/TRegExpr/commit/ef3880a4f035e2c5ca58c0ab4d40fc9cc8e17900
