### ISSUE TITLE
Suggest: Fixes to get working on never versions of Delphi

### ISSUE THREAD

**Issue by TommySlokky** [masterandrey/TRegExpr#6]
- The new solution for regular expressions in Delphi has some serious drawback as well - in particular in e.g. XE2-XE4 when dealing with UCS-2 documents and is not maintained by 4d party so people can not upgrade that lib without buying new Delphi versions. 
- I want to have cross-compile code in Delphi and Lazarus. This is an important goal I think and very easy to reach.

I suggest adding these changes to the RegXepr unit:

```
{$IFDEF VER170} {$DEFINE D7} {$DEFINE D6} {$DEFINE D5} {$DEFINE D4} {$DEFINE D3} {$DEFINE D2} {$ENDIF} // D7
{$IFDEF VER180} {$DEFINE D7} {$DEFINE D6} {$DEFINE D5} {$DEFINE D4} {$DEFINE D3} {$DEFINE D2} {$ENDIF} // D7
{$IFDEF VER200} {$DEFINE D7} {$DEFINE D6} {$DEFINE D5} {$DEFINE D4} {$DEFINE D3} {$DEFINE D2} {$ENDIF} // D7
{$IFDEF VER210} {$DEFINE UniCode} {$DEFINE D7} {$DEFINE D6} {$DEFINE D5} {$DEFINE D4} {$DEFINE D3} {$DEFINE D2} {$ENDIF} // D7
{$IFDEF VER220} {$DEFINE UniCode} {$DEFINE D7} {$DEFINE D6} {$DEFINE D5} {$DEFINE D4} {$DEFINE D3} {$DEFINE D2} {$ENDIF} // D7
{$IFDEF VER230} {$DEFINE UniCode} {$DEFINE D7} {$DEFINE D6} {$DEFINE D5} {$DEFINE D4} {$DEFINE D3} {$DEFINE D2} {$ENDIF} // D7
{$IFDEF VER240} {$DEFINE UniCode} {$DEFINE D7} {$DEFINE D6} {$DEFINE D5} {$DEFINE D4} {$DEFINE D3} {$DEFINE D2} {$ENDIF} // D7
{$IFDEF VER250} {$DEFINE UniCode} {$DEFINE D7} {$DEFINE D6} {$DEFINE D5} {$DEFINE D4} {$DEFINE D3} {$DEFINE D2} {$ENDIF} // D7
{$IFDEF VER260} {$DEFINE UniCode} {$DEFINE D7} {$DEFINE D6} {$DEFINE D5} {$DEFINE D4} {$DEFINE D3} {$DEFINE D2} {$ENDIF} // D7
{$IFDEF VER270} {$DEFINE UniCode} {$DEFINE D7} {$DEFINE D6} {$DEFINE D5} {$DEFINE D4} {$DEFINE D3} {$DEFINE D2} {$ENDIF} // D7
{$IFDEF VER280} {$DEFINE UniCode} {$DEFINE D7} {$DEFINE D6} {$DEFINE D5} {$DEFINE D4} {$DEFINE D3} {$DEFINE D2} {$ENDIF} // D7

```
and maybe

```
{$IFDEF D7} {$DEFINE UseAsserts} {$ENDIF}

```

_Extra:_
I would also suggest increase this to 63 instead of 15 (you 15 really fast - in practice 63 holds even when used intensively over 10+ years)

`NSUBEXP = 63;`

**Comment by masterandrey** [comment]
Could you commit this changes to the github?
For many years I had not using Delphi and do not have working pascal environment, so I cannot check even simplest change.
Some TRegExpr version is in Free pascal, may be better commit to free pascal.

**Comment by Skif-off** [comment]
@TommySlokky

> I would also suggest increase this to 63 instead of 15 (you 15 really fast - in practice 63 holds even when used intensively over 10+ years)

FPC uses ```NSUBEXP = 90``` (see [SVN](https://svn.freepascal.org/svn/fpc/trunk/packages/regexpr/src/regexpr.pas) or [here](https://github.com/graemeg/freepascal/blob/master/packages/regexpr/src/regexpr.pas), with syntax highlight).

**Comment by masterandrey** [comment]
Thank you! At the moment I do not have environment to check fixes.Could you please test them and send by as pull request on github? Andrey 04.06.2018, 22:32, "Skif-off" <notifications@github.com>:@TommySlokkyI would also suggest increase this to 63 instead of 15 (you 15 really fast - in practice 63 holds even when used intensively over 10+ years)FPC uses NSUBEXP = 90 (see SVN or here, with syntax highlight).—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by TommySlokky** [comment]
Sorry - I will look into this but I do not usually using any versioning system since I am the only person on my projects - still I guess I just as well can get used to GitHUB/SVN/etc.. 

FPC/Lazarus is great, but for cross Delphi/Lazarus the changes would still need to be applied.

**Comment by masterandrey** [comment]
https://github.com/masterandrey/TRegExpr/commit/671f75839e8c9d688232603a4878f6092da68bbe
Increased number of subexpression

Other changes I suggest to place to other tickets so we will have clear change history
